"""Deployment workflow state.

Persisted in ADK session state across the full agent pipeline.
"""

from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, Field


class AnomalySignal(BaseModel):
    """Structured anomaly signal from Deploy Monitor Agent."""

    severity: Literal["LOW", "MEDIUM", "HIGH", "CRITICAL"]
    confidence: float = Field(ge=0.0, le=1.0)
    affected_metrics: list[str]
    evidence: list[dict[str, Any]]  # [{metric, baseline, current, ratio}]
    detected_at: datetime


class DecisionTrace(BaseModel):
    """Auditable decision trace from Decision Agent."""

    trace_id: str
    decision: Literal["wait", "alert", "rollback"]
    confidence: float = Field(ge=0.0, le=1.0)
    evidence_summary: str
    policy_checks: dict[str, bool]  # {check_name: bool}
    policy_passed: bool
    authorized: bool
    authorization_reason: str
    decided_at: datetime


class PostmortemReport(BaseModel):
    """Structured SRE Postmortem Document generated by Postmortem Agent."""

    report_id: str
    deployment_id: str
    service_name: str
    created_at: datetime
    target_version: str
    stable_version: str
    incident_duration_seconds: float
    severity: Literal["LOW", "MEDIUM", "HIGH", "CRITICAL"]
    outcome: Literal["recovered", "failed_rollback", "policy_blocked"]
    executive_summary: str
    root_cause_analysis: str
    timeline_events: list[dict[str, Any]] = Field(default_factory=list)
    metric_deltas: dict[str, dict[str, Any]] = Field(default_factory=dict)
    decision_summary: dict[str, Any] = Field(default_factory=dict)
    rollback_summary: dict[str, Any] = Field(default_factory=dict)
    preventative_actions: list[str] = Field(default_factory=list)
    trace_id: str | None = None

    def to_markdown(self) -> str:
        """Render publication-ready SRE Incident Postmortem Markdown."""
        lines = [
            f"# Incident Postmortem: {self.service_name} ({self.report_id})",
            "",
            f"**Service:** `{self.service_name}` | **Severity:** `{self.severity}` | **Outcome:** `{self.outcome}`",
            f"**Date:** {self.created_at.strftime('%Y-%m-%d %H:%M:%S UTC')} | **Duration:** {self.incident_duration_seconds:.1f}s",
            f"**Target Version:** `{self.target_version}` | **Stable Rollback:** `{self.stable_version}`",
            f"**Trace ID:** `{self.trace_id or 'N/A'}`",
            "",
            "## Executive Summary",
            self.executive_summary,
            "",
            "## Root Cause Analysis (5 Whys)",
            self.root_cause_analysis,
            "",
            "## Anomaly & Telemetry Evidence",
            "| Metric | Baseline | Incident Peak | Delta % | Status |",
            "| :--- | :--- | :--- | :--- | :--- |",
        ]

        for metric, delta in self.metric_deltas.items():
            base = delta.get("baseline", "N/A")
            current = delta.get("current", "N/A")
            ratio = delta.get("ratio", 1.0)
            pct = f"+{(ratio - 1.0) * 100:.1f}%" if isinstance(ratio, (int, float)) and ratio >= 1 else f"{(ratio - 1.0) * 100:.1f}%"
            status = "ANOMALY" if isinstance(ratio, (int, float)) and ratio > 1.2 else "NORMAL"
            lines.append(f"| {metric} | {base} | {current} | {pct} | {status} |")

        lines.extend([
            "",
            "## Incident Timeline",
        ])
        for event in self.timeline_events:
            ts = event.get("timestamp", "")
            stage = event.get("stage", "Event")
            desc = event.get("description", "")
            lines.append(f"- **{ts}** `[{stage}]`: {desc}")

        lines.extend([
            "",
            "## Governed Decision & Recovery Actions",
            f"- **Decision:** `{self.decision_summary.get('decision', 'N/A')}` (Confidence: {self.decision_summary.get('confidence', 0.0):.2f})",
            f"- **Policy Checks:** {self.decision_summary.get('policy_passed', False)}",
            f"- **Rollback Operation:** `{self.rollback_summary.get('operation_id', 'N/A')}` (Target: `{self.rollback_summary.get('target_version', 'N/A')}`)",
            "",
            "## Preventative Action Items",
        ])
        for action in self.preventative_actions:
            lines.append(f"- [ ] {action}")

        return "\n".join(lines)


class DeploymentWorkflowState(BaseModel):
    """Persistent state across the DeployGuard deployment-to-recovery lifecycle.

    Serialized to/from ADK ctx.session.state as a dict.
    """

    # Deployment identity
    deployment_id: str
    service_name: str
    version: str
    environment: Literal["development", "staging", "production"] = "production"
    deployed_at: datetime

    # Pipeline status (updated by each agent)
    pipeline_status: Literal[
        "monitoring",
        "anomaly_detected",
        "investigating",
        "decision_made",
        "rolling_back",
        "verifying_recovery",
        "complete",
        "failed",
    ] = "monitoring"

    # Deploy Monitor results
    baseline_metrics: dict[str, Any] | None = None
    current_metrics: dict[str, Any] | None = None
    anomaly_signal: AnomalySignal | None = None

    # Decision Agent results
    decision_trace: DecisionTrace | None = None

    # Rollback Agent results
    rollback_authorized: bool | None = None
    rollback_executed: bool | None = None
    rollback_target_version: str | None = None
    rollback_operation_id: str | None = None

    # Recovery verification
    recovery_verdict: Literal["recovered", "degraded", "inconclusive"] | None = None
    recovery_checked_at: datetime | None = None

    # Postmortem
    postmortem_id: str | None = None
    postmortem_report: PostmortemReport | None = None

    def to_session_dict(self) -> dict[str, Any]:
        """Serialize for storage in ADK ctx.session.state."""
        return self.model_dump(mode="json")

    @classmethod
    def from_session_dict(cls, data: dict[str, Any]) -> "DeploymentWorkflowState":
        """Deserialize from ADK ctx.session.state."""
        return cls.model_validate(data)
